### ISSUE TITLE
Applications data

### ISSUE THREAD

**Issue by jlprol** [jiafengkevinchen/logs-public#1]
Can you upload the data for the empirical applications section (paper3.dta, Bribes_Regressions.dta and paper10.dta), so we don't have to run the bash script main.sh?
Thank you.

**Comment by jonathandroth** [comment]
Paper 3: https://www.dropbox.com/scl/fi/vikamj4nhr71u3phnjwtk/paper3.dta?rlkey=zzbrw48a0548ongl9gllslyww&dl=0

Paper 10: https://www.dropbox.com/scl/fi/c0qapgvrnim9et0nsx3t7/paper10.dta?rlkey=5x8lyj3k6aqnul13wqyum0e3g&dl=0

Bribes regression: https://www.dropbox.com/scl/fi/i2fnecduj330j4o0o9rij/Bribes_Regressions.dta?rlkey=vobsjm91bwknyskwgsqnoejm5&dl=0

They should also be on the QJE dataverse.
